@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMjNAZ20uY29tIiwiaWQiOiI2MGMyNjAxOTkwZmI5MzY2OThiYWI5MjEiLCJpYXQiOjE2MjQxNzcwNzZ9.-pVunzUhhReGwnsXC2dTnBGz5efkWdZo04GU70P6jFU

###

GET {{host}}/event/list/all HTTP/1.1
Authorization: Bearer {{token}}

###

GET {{host}}/event/my/list HTTP/1.1
Authorization: Bearer {{token}}
