@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJvbmVAZ20uY29tIiwiaWQiOiI2MGQ3NWEzMzI1MmI2ZjM3NDA1YzQ1NmMiLCJpYXQiOjE2MjQ3NjA1MzR9.BWf4Ll2rd4kB_DIVsQ3PqgVTbJeueUoITPRa9QlwGjo

###

GET {{host}}/event/list/all HTTP/1.1
Authorization: Bearer {{token}}

###

GET {{host}}/event/my/list HTTP/1.1
Authorization: Bearer {{token}}
