@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMjNAZ20uY29tIiwiaWQiOiI2MGMyNjAxOTkwZmI5MzY2OThiYWI5MjEiLCJpYXQiOjE2MjQ2ODIwMjJ9.FCafhHMnPGOj-11I2Z7HIevCxnxhJ_mGsJ0B0pKjMa0
@personalHabitId = 60c5014552159b157c75ab24
@historyHabitId = historyHabitId
###

GET {{host}}/habit/my/list HTTP/1.1
Authorization: Bearer {{token}}

###
# GET {{host}}/habit/my/60c260e290fb936698bab925 HTTP/1.1
# Authorization: Bearer {{token}}

###
GET {{host}}/habit/my/list/2021-06-14 HTTP/1.1
Authorization: Bearer {{token}}

###
GET {{host}}/habit/my/{{personalHabitId}}/progress
Authorization: Bearer {{token}}

###
POST {{host}}/habit HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "authorId":"60c2601990fb936698bab921",
    "title":"Habit one",
    "description":"info one"
}

###
PUT {{host}}/habit/edit/{{personalHabitId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "description":"edited info"
}
###

PUT {{host}}/habit/my/progress/{{historyHabitId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "progress": 0,
    "completed":false
}

###
DELETE {{host}}/habit/my/{{personalHabitId}} HTTP/1.1
Authorization: Bearer {{token}}
