@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMjNAZ20uY29tIiwiaWQiOiI2MGE1MWNlNTBiM2Q4NTMyNjRhNWE0MTkiLCJpYXQiOjE2MjE1MTk2OTgsImV4cCI6MTYyMTYwNjA5OH0.vdsjTwJ9oEnX1vY8k2eRkGsvxpwnISxkVmfmD-YHuN0

###

GET {{host}}/post/list/all HTTP/1.1
Authorization: Bearer {{token}}

###

